# Generated by Django 3.1.1 on 2020-09-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20200922_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Room')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='Room',
            field=models.ManyToManyField(to='units.Room'),
        ),
    ]
