# Generated by Django 3.1.1 on 2020-09-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20200923_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RANTED', 'RANTED')], default='AVAILABLE', max_length=20),
        ),
    ]
