# Generated by Django 3.1.1 on 2020-09-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE TO RENT', 'AVAILABLE TO RENT'), ('RENTED', 'RENTED'), ('AVAILABLE TO SELL', 'AVAILABLE TO SELL'), ('SOLD', 'SOLD'), ('SUSPENDED', 'SUSPENDED')], default='SUSPENDED', max_length=20),
        ),
    ]
