# Generated by Django 3.1.1 on 2020-09-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_auto_20200923_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='remarks',
            field=models.TextField(default='', max_length=500, verbose_name='Remarks'),
            preserve_default=False,
        ),
    ]
