# Generated by Django 3.1.1 on 2020-09-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_unit_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='Unit Title'),
        ),
    ]
